//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.06.22 at 06:38:05 PM MDT 
//


package gov.va.vba.framework.domain.entities.jaxb.ro;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the gov.va.vba.framework.domain.entities.jaxb.ro package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gov.va.vba.framework.domain.entities.jaxb.ro
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CityCntyState }
     * 
     */
    public CityCntyState createCityCntyState() {
        return new CityCntyState();
    }

    /**
     * Create an instance of {@link ForeignCntries }
     * 
     */
    public ForeignCntries createForeignCntries() {
        return new ForeignCntries();
    }

    /**
     * Create an instance of {@link RegionState }
     * 
     */
    public RegionState createRegionState() {
        return new RegionState();
    }

    /**
     * Create an instance of {@link RO }
     * 
     */
    public RO createRO() {
        return new RO();
    }

    /**
     * Create an instance of {@link ROMappingProfileType }
     * 
     */
    public ROMappingProfileType createROMappingProfileType() {
        return new ROMappingProfileType();
    }

    /**
     * Create an instance of {@link ZipCodes }
     * 
     */
    public ZipCodes createZipCodes() {
        return new ZipCodes();
    }

}
