//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.06.22 at 06:38:05 PM MDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://ro.jaxb.entities.domain.framework.vba.va.gov/")
package gov.va.vba.framework.domain.entities.jaxb.ro;
