//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.06.22 at 06:38:05 PM MDT 
//


package gov.va.vba.framework.domain.entities.jaxb.ro;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RONum" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ROName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "roNum",
    "roName"
})
@XmlRootElement(name = "RO")
public class RO {

    @XmlElement(name = "RONum", required = true)
    protected String roNum;
    @XmlElement(name = "ROName", required = true)
    protected String roName;

    /**
     * Gets the value of the roNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRONum() {
        return roNum;
    }

    /**
     * Sets the value of the roNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRONum(String value) {
        this.roNum = value;
    }

    /**
     * Gets the value of the roName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getROName() {
        return roName;
    }

    /**
     * Sets the value of the roName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setROName(String value) {
        this.roName = value;
    }

}
