//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.06.22 at 06:38:05 PM MDT 
//


package gov.va.vba.framework.domain.entities.jaxb.ro;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://ro.jaxb.entities.domain.framework.vba.va.gov/}CityCntyState" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://ro.jaxb.entities.domain.framework.vba.va.gov/}ForeignCntries" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://ro.jaxb.entities.domain.framework.vba.va.gov/}RO" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://ro.jaxb.entities.domain.framework.vba.va.gov/}ZipCodes" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://ro.jaxb.entities.domain.framework.vba.va.gov/}RegionState" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cityCntyState",
    "foreignCntries",
    "ro",
    "zipCodes",
    "regionState"
})
@XmlRootElement(name = "ROMappingProfileType")
public class ROMappingProfileType {

    @XmlElement(name = "CityCntyState", namespace = "http://ro.jaxb.entities.domain.framework.vba.va.gov/")
    protected List<CityCntyState> cityCntyState;
    @XmlElement(name = "ForeignCntries", namespace = "http://ro.jaxb.entities.domain.framework.vba.va.gov/")
    protected List<ForeignCntries> foreignCntries;
    @XmlElement(name = "RO", namespace = "http://ro.jaxb.entities.domain.framework.vba.va.gov/")
    protected List<RO> ro;
    @XmlElement(name = "ZipCodes", namespace = "http://ro.jaxb.entities.domain.framework.vba.va.gov/")
    protected List<ZipCodes> zipCodes;
    @XmlElement(name = "RegionState", namespace = "http://ro.jaxb.entities.domain.framework.vba.va.gov/")
    protected List<RegionState> regionState;

    /**
     * Gets the value of the cityCntyState property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cityCntyState property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCityCntyState().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CityCntyState }
     * 
     * 
     */
    public List<CityCntyState> getCityCntyState() {
        if (cityCntyState == null) {
            cityCntyState = new ArrayList<CityCntyState>();
        }
        return this.cityCntyState;
    }

    /**
     * Gets the value of the foreignCntries property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the foreignCntries property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getForeignCntries().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ForeignCntries }
     * 
     * 
     */
    public List<ForeignCntries> getForeignCntries() {
        if (foreignCntries == null) {
            foreignCntries = new ArrayList<ForeignCntries>();
        }
        return this.foreignCntries;
    }

    /**
     * Gets the value of the ro property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ro property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRO().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RO }
     * 
     * 
     */
    public List<RO> getRO() {
        if (ro == null) {
            ro = new ArrayList<RO>();
        }
        return this.ro;
    }

    /**
     * Gets the value of the zipCodes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the zipCodes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getZipCodes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ZipCodes }
     * 
     * 
     */
    public List<ZipCodes> getZipCodes() {
        if (zipCodes == null) {
            zipCodes = new ArrayList<ZipCodes>();
        }
        return this.zipCodes;
    }

    /**
     * Gets the value of the regionState property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the regionState property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRegionState().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RegionState }
     * 
     * 
     */
    public List<RegionState> getRegionState() {
        if (regionState == null) {
            regionState = new ArrayList<RegionState>();
        }
        return this.regionState;
    }

}
