//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.01.19 at 10:54:03 AM CST 
//


package gov.va.vba.framework.domain.entities.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PRIOR_FIRST_NAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PRIOR_LAST_NAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "priorfirstname",
    "priorlastname"
})
@XmlRootElement(name = "ALIAS_NAME")
public class ALIASNAME {

    @XmlElement(name = "PRIOR_FIRST_NAME", required = true)
    protected String priorfirstname;
    @XmlElement(name = "PRIOR_LAST_NAME", required = true)
    protected String priorlastname;

    /**
     * Gets the value of the priorfirstname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPRIORFIRSTNAME() {
        return priorfirstname;
    }

    /**
     * Sets the value of the priorfirstname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPRIORFIRSTNAME(String value) {
        this.priorfirstname = value;
    }

    /**
     * Gets the value of the priorlastname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPRIORLASTNAME() {
        return priorlastname;
    }

    /**
     * Sets the value of the priorlastname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPRIORLASTNAME(String value) {
        this.priorlastname = value;
    }

}
