//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.01.19 at 10:54:03 AM CST 
//


package gov.va.vba.framework.domain.entities.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="EDUCATION_LEVEL_DATE" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="EDUCATION_LEVEL_CODE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "educationleveldate",
    "educationlevelcode"
})
@XmlRootElement(name = "EDUCATION")
public class EDUCATION {

    @XmlElement(name = "EDUCATION_LEVEL_DATE", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar educationleveldate;
    @XmlElement(name = "EDUCATION_LEVEL_CODE", required = true)
    protected String educationlevelcode;

    /**
     * Gets the value of the educationleveldate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEDUCATIONLEVELDATE() {
        return educationleveldate;
    }

    /**
     * Sets the value of the educationleveldate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEDUCATIONLEVELDATE(XMLGregorianCalendar value) {
        this.educationleveldate = value;
    }

    /**
     * Gets the value of the educationlevelcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEDUCATIONLEVELCODE() {
        return educationlevelcode;
    }

    /**
     * Sets the value of the educationlevelcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEDUCATIONLEVELCODE(String value) {
        this.educationlevelcode = value;
    }

}
