//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.01.19 at 10:54:03 AM CST 
//


package gov.va.vba.framework.domain.entities.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ADDRESS_LINE_ONE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ADDRESS_LINE_TWO" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CITY" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="STATE_CODE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ZIP_CODE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ZIP_CODE_EXT" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "addresslineone",
    "addresslinetwo",
    "city",
    "statecode",
    "zipcode",
    "zipcodeext"
})
@XmlRootElement(name = "MAILING_ADDRESS")
public class MAILINGADDRESS {

    @XmlElement(name = "ADDRESS_LINE_ONE", required = true)
    protected String addresslineone;
    @XmlElement(name = "ADDRESS_LINE_TWO", required = true)
    protected String addresslinetwo;
    @XmlElement(name = "CITY", required = true)
    protected String city;
    @XmlElement(name = "STATE_CODE", required = true)
    protected String statecode;
    @XmlElement(name = "ZIP_CODE", required = true)
    protected String zipcode;
    @XmlElement(name = "ZIP_CODE_EXT", required = true)
    protected String zipcodeext;

    /**
     * Gets the value of the addresslineone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getADDRESSLINEONE() {
        return addresslineone;
    }

    /**
     * Sets the value of the addresslineone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setADDRESSLINEONE(String value) {
        this.addresslineone = value;
    }

    /**
     * Gets the value of the addresslinetwo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getADDRESSLINETWO() {
        return addresslinetwo;
    }

    /**
     * Sets the value of the addresslinetwo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setADDRESSLINETWO(String value) {
        this.addresslinetwo = value;
    }

    /**
     * Gets the value of the city property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCITY() {
        return city;
    }

    /**
     * Sets the value of the city property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCITY(String value) {
        this.city = value;
    }

    /**
     * Gets the value of the statecode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTATECODE() {
        return statecode;
    }

    /**
     * Sets the value of the statecode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTATECODE(String value) {
        this.statecode = value;
    }

    /**
     * Gets the value of the zipcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZIPCODE() {
        return zipcode;
    }

    /**
     * Sets the value of the zipcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZIPCODE(String value) {
        this.zipcode = value;
    }

    /**
     * Gets the value of the zipcodeext property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZIPCODEEXT() {
        return zipcodeext;
    }

    /**
     * Sets the value of the zipcodeext property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZIPCODEEXT(String value) {
        this.zipcodeext = value;
    }

}
