//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.6-2.1.6-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.01.13 at 01:54:05 PM CST 
//


package gov.va.vba.framework.domain.entities.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for MilitaryServiceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MilitaryServiceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="VA_Office_Records_Location" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="form" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Military_Service_Number" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="form" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Service_Branch_Name" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="form" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Date_Entered_Active_Duty" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="Date_Left_Active_Duty" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="Separated_From_Service" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Pay_Grade_Type_Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Type_of_Separation_Or_Discharge" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Military_Theaters_Served" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MilitaryServiceType", propOrder = {
    "vaOfficeRecordsLocation",
    "militaryServiceNumber",
    "serviceBranchName",
    "dateEnteredActiveDuty",
    "dateLeftActiveDuty",
    "separatedFromService",
    "payGradeTypeName",
    "typeOfSeparationOrDischarge",
    "militaryTheatersServed"
})
public class MilitaryServiceType {

    @XmlElement(name = "VA_Office_Records_Location")
    protected MilitaryServiceType.VAOfficeRecordsLocation vaOfficeRecordsLocation;
    @XmlElement(name = "Military_Service_Number")
    protected MilitaryServiceType.MilitaryServiceNumber militaryServiceNumber;
    @XmlElement(name = "Service_Branch_Name")
    protected MilitaryServiceType.ServiceBranchName serviceBranchName;
    @XmlElement(name = "Date_Entered_Active_Duty")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dateEnteredActiveDuty;
    @XmlElement(name = "Date_Left_Active_Duty")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dateLeftActiveDuty;
    @XmlElement(name = "Separated_From_Service")
    protected String separatedFromService;
    @XmlElement(name = "Pay_Grade_Type_Name")
    protected String payGradeTypeName;
    @XmlElement(name = "Type_of_Separation_Or_Discharge")
    protected String typeOfSeparationOrDischarge;
    @XmlElement(name = "Military_Theaters_Served")
    protected List<String> militaryTheatersServed;

    /**
     * Gets the value of the vaOfficeRecordsLocation property.
     * 
     * @return
     *     possible object is
     *     {@link MilitaryServiceType.VAOfficeRecordsLocation }
     *     
     */
    public MilitaryServiceType.VAOfficeRecordsLocation getVAOfficeRecordsLocation() {
        return vaOfficeRecordsLocation;
    }

    /**
     * Sets the value of the vaOfficeRecordsLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link MilitaryServiceType.VAOfficeRecordsLocation }
     *     
     */
    public void setVAOfficeRecordsLocation(MilitaryServiceType.VAOfficeRecordsLocation value) {
        this.vaOfficeRecordsLocation = value;
    }

    /**
     * Gets the value of the militaryServiceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link MilitaryServiceType.MilitaryServiceNumber }
     *     
     */
    public MilitaryServiceType.MilitaryServiceNumber getMilitaryServiceNumber() {
        return militaryServiceNumber;
    }

    /**
     * Sets the value of the militaryServiceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link MilitaryServiceType.MilitaryServiceNumber }
     *     
     */
    public void setMilitaryServiceNumber(MilitaryServiceType.MilitaryServiceNumber value) {
        this.militaryServiceNumber = value;
    }

    /**
     * Gets the value of the serviceBranchName property.
     * 
     * @return
     *     possible object is
     *     {@link MilitaryServiceType.ServiceBranchName }
     *     
     */
    public MilitaryServiceType.ServiceBranchName getServiceBranchName() {
        return serviceBranchName;
    }

    /**
     * Sets the value of the serviceBranchName property.
     * 
     * @param value
     *     allowed object is
     *     {@link MilitaryServiceType.ServiceBranchName }
     *     
     */
    public void setServiceBranchName(MilitaryServiceType.ServiceBranchName value) {
        this.serviceBranchName = value;
    }

    /**
     * Gets the value of the dateEnteredActiveDuty property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateEnteredActiveDuty() {
        return dateEnteredActiveDuty;
    }

    /**
     * Sets the value of the dateEnteredActiveDuty property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateEnteredActiveDuty(XMLGregorianCalendar value) {
        this.dateEnteredActiveDuty = value;
    }

    /**
     * Gets the value of the dateLeftActiveDuty property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateLeftActiveDuty() {
        return dateLeftActiveDuty;
    }

    /**
     * Sets the value of the dateLeftActiveDuty property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateLeftActiveDuty(XMLGregorianCalendar value) {
        this.dateLeftActiveDuty = value;
    }

    /**
     * Gets the value of the separatedFromService property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSeparatedFromService() {
        return separatedFromService;
    }

    /**
     * Sets the value of the separatedFromService property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSeparatedFromService(String value) {
        this.separatedFromService = value;
    }

    /**
     * Gets the value of the payGradeTypeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPayGradeTypeName() {
        return payGradeTypeName;
    }

    /**
     * Sets the value of the payGradeTypeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPayGradeTypeName(String value) {
        this.payGradeTypeName = value;
    }

    /**
     * Gets the value of the typeOfSeparationOrDischarge property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypeOfSeparationOrDischarge() {
        return typeOfSeparationOrDischarge;
    }

    /**
     * Sets the value of the typeOfSeparationOrDischarge property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypeOfSeparationOrDischarge(String value) {
        this.typeOfSeparationOrDischarge = value;
    }

    /**
     * Gets the value of the militaryTheatersServed property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the militaryTheatersServed property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMilitaryTheatersServed().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getMilitaryTheatersServed() {
        if (militaryTheatersServed == null) {
            militaryTheatersServed = new ArrayList<String>();
        }
        return this.militaryTheatersServed;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="form" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class MilitaryServiceNumber {

        @XmlValue
        protected String value;
        @XmlAttribute
        @XmlSchemaType(name = "anySimpleType")
        protected String form;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the form property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getForm() {
            return form;
        }

        /**
         * Sets the value of the form property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setForm(String value) {
            this.form = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="form" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class ServiceBranchName {

        @XmlValue
        protected String value;
        @XmlAttribute
        @XmlSchemaType(name = "anySimpleType")
        protected String form;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the form property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getForm() {
            return form;
        }

        /**
         * Sets the value of the form property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setForm(String value) {
            this.form = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="form" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class VAOfficeRecordsLocation {

        @XmlValue
        protected String value;
        @XmlAttribute
        @XmlSchemaType(name = "anySimpleType")
        protected String form;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the form property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getForm() {
            return form;
        }

        /**
         * Sets the value of the form property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setForm(String value) {
            this.form = value;
        }

    }

}
