//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.6-2.1.6-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.01.13 at 01:54:05 PM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://vonapps.vba.va.gov/")
package gov.va.vba.framework.domain.entities.jaxb;
