//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.01.19 at 10:54:03 AM CST 
//


package gov.va.vba.framework.domain.entities.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SEGMENT_ID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PAY_PLAN_CODE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PAGE_CD" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "segmentid",
    "payplancode",
    "pagecd"
})
@XmlRootElement(name = "PAGE")
public class PAGE {

    @XmlElement(name = "SEGMENT_ID", required = true)
    protected String segmentid;
    @XmlElement(name = "PAY_PLAN_CODE", required = true)
    protected String payplancode;
    @XmlElement(name = "PAGE_CD", required = true)
    protected String pagecd;

    /**
     * Gets the value of the segmentid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSEGMENTID() {
        return segmentid;
    }

    /**
     * Sets the value of the segmentid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSEGMENTID(String value) {
        this.segmentid = value;
    }

    /**
     * Gets the value of the payplancode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPAYPLANCODE() {
        return payplancode;
    }

    /**
     * Sets the value of the payplancode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPAYPLANCODE(String value) {
        this.payplancode = value;
    }

    /**
     * Gets the value of the pagecd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPAGECD() {
        return pagecd;
    }

    /**
     * Sets the value of the pagecd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPAGECD(String value) {
        this.pagecd = value;
    }

}
