//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.01.19 at 10:54:03 AM CST 
//


package gov.va.vba.framework.domain.entities.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ORGANIZATION_CODE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CATEGORY_CODE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SEGMENT_ID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SERVICE_CODE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="BEGIN_DATE" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="PE_DATE" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="TERM_DATE" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "organizationcode",
    "categorycode",
    "segmentid",
    "servicecode",
    "begindate",
    "pedate",
    "termdate"
})
@XmlRootElement(name = "PERSONNEL")
public class PERSONNEL {

    @XmlElement(name = "ORGANIZATION_CODE", required = true)
    protected String organizationcode;
    @XmlElement(name = "CATEGORY_CODE", required = true)
    protected String categorycode;
    @XmlElement(name = "SEGMENT_ID", required = true)
    protected String segmentid;
    @XmlElement(name = "SERVICE_CODE", required = true)
    protected String servicecode;
    @XmlElement(name = "BEGIN_DATE", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar begindate;
    @XmlElement(name = "PE_DATE", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar pedate;
    @XmlElement(name = "TERM_DATE", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar termdate;

    /**
     * Gets the value of the organizationcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getORGANIZATIONCODE() {
        return organizationcode;
    }

    /**
     * Sets the value of the organizationcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setORGANIZATIONCODE(String value) {
        this.organizationcode = value;
    }

    /**
     * Gets the value of the categorycode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCATEGORYCODE() {
        return categorycode;
    }

    /**
     * Sets the value of the categorycode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCATEGORYCODE(String value) {
        this.categorycode = value;
    }

    /**
     * Gets the value of the segmentid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSEGMENTID() {
        return segmentid;
    }

    /**
     * Sets the value of the segmentid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSEGMENTID(String value) {
        this.segmentid = value;
    }

    /**
     * Gets the value of the servicecode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSERVICECODE() {
        return servicecode;
    }

    /**
     * Sets the value of the servicecode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSERVICECODE(String value) {
        this.servicecode = value;
    }

    /**
     * Gets the value of the begindate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getBEGINDATE() {
        return begindate;
    }

    /**
     * Sets the value of the begindate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setBEGINDATE(XMLGregorianCalendar value) {
        this.begindate = value;
    }

    /**
     * Gets the value of the pedate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPEDATE() {
        return pedate;
    }

    /**
     * Sets the value of the pedate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPEDATE(XMLGregorianCalendar value) {
        this.pedate = value;
    }

    /**
     * Gets the value of the termdate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTERMDATE() {
        return termdate;
    }

    /**
     * Sets the value of the termdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTERMDATE(XMLGregorianCalendar value) {
        this.termdate = value;
    }

}
