//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.01.19 at 10:54:03 AM CST 
//


package gov.va.vba.framework.domain.entities.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="VA_ID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="FIRST_NAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MIDDLE_NAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="LAST_NAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PN_ID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SEX" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="BIRTH_DATE" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="MARITAL_STATUS" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DEATH_DATE" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="ID_TYPE_CODE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "vaid",
    "firstname",
    "middlename",
    "lastname",
    "pnid",
    "sex",
    "birthdate",
    "maritalstatus",
    "deathdate",
    "idtypecode"
})
@XmlRootElement(name = "PERSONV")
public class PERSONV {

    @XmlElement(name = "VA_ID", required = true)
    protected String vaid;
    @XmlElement(name = "FIRST_NAME", required = true)
    protected String firstname;
    @XmlElement(name = "MIDDLE_NAME", required = true)
    protected String middlename;
    @XmlElement(name = "LAST_NAME", required = true)
    protected String lastname;
    @XmlElement(name = "PN_ID", required = true)
    protected String pnid;
    @XmlElement(name = "SEX", required = true)
    protected String sex;
    @XmlElement(name = "BIRTH_DATE", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar birthdate;
    @XmlElement(name = "MARITAL_STATUS", required = true)
    protected String maritalstatus;
    @XmlElement(name = "DEATH_DATE", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar deathdate;
    @XmlElement(name = "ID_TYPE_CODE", required = true)
    protected String idtypecode;

    /**
     * Gets the value of the vaid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVAID() {
        return vaid;
    }

    /**
     * Sets the value of the vaid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVAID(String value) {
        this.vaid = value;
    }

    /**
     * Gets the value of the firstname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFIRSTNAME() {
        return firstname;
    }

    /**
     * Sets the value of the firstname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFIRSTNAME(String value) {
        this.firstname = value;
    }

    /**
     * Gets the value of the middlename property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMIDDLENAME() {
        return middlename;
    }

    /**
     * Sets the value of the middlename property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMIDDLENAME(String value) {
        this.middlename = value;
    }

    /**
     * Gets the value of the lastname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLASTNAME() {
        return lastname;
    }

    /**
     * Sets the value of the lastname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLASTNAME(String value) {
        this.lastname = value;
    }

    /**
     * Gets the value of the pnid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPNID() {
        return pnid;
    }

    /**
     * Sets the value of the pnid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPNID(String value) {
        this.pnid = value;
    }

    /**
     * Gets the value of the sex property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSEX() {
        return sex;
    }

    /**
     * Sets the value of the sex property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSEX(String value) {
        this.sex = value;
    }

    /**
     * Gets the value of the birthdate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getBIRTHDATE() {
        return birthdate;
    }

    /**
     * Sets the value of the birthdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setBIRTHDATE(XMLGregorianCalendar value) {
        this.birthdate = value;
    }

    /**
     * Gets the value of the maritalstatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMARITALSTATUS() {
        return maritalstatus;
    }

    /**
     * Sets the value of the maritalstatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMARITALSTATUS(String value) {
        this.maritalstatus = value;
    }

    /**
     * Gets the value of the deathdate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDEATHDATE() {
        return deathdate;
    }

    /**
     * Sets the value of the deathdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDEATHDATE(XMLGregorianCalendar value) {
        this.deathdate = value;
    }

    /**
     * Gets the value of the idtypecode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIDTYPECODE() {
        return idtypecode;
    }

    /**
     * Sets the value of the idtypecode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIDTYPECODE(String value) {
        this.idtypecode = value;
    }

}
