//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.6-2.1.6-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.01.13 at 01:54:05 PM CST 
//


package gov.va.vba.framework.domain.entities.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for SpouseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SpouseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Spouse_Name" type="{http://vonapps.vba.va.gov/}NameType"/>
 *         &lt;element name="Social_Security_Num" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="File_Number" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Birth_Date" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="Postal" type="{http://vonapps.vba.va.gov/}PostalType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SpouseType", propOrder = {
    "spouseName",
    "socialSecurityNum",
    "fileNumber",
    "birthDate",
    "postal"
})
public class SpouseType {

    @XmlElement(name = "Spouse_Name", required = true)
    protected NameType spouseName;
    @XmlElement(name = "Social_Security_Num", required = true, nillable = true)
    protected String socialSecurityNum;
    @XmlElement(name = "File_Number", required = true, nillable = true)
    protected String fileNumber;
    @XmlElement(name = "Birth_Date", required = true, nillable = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar birthDate;
    @XmlElement(name = "Postal", required = true)
    protected PostalType postal;

    /**
     * Gets the value of the spouseName property.
     * 
     * @return
     *     possible object is
     *     {@link NameType }
     *     
     */
    public NameType getSpouseName() {
        return spouseName;
    }

    /**
     * Sets the value of the spouseName property.
     * 
     * @param value
     *     allowed object is
     *     {@link NameType }
     *     
     */
    public void setSpouseName(NameType value) {
        this.spouseName = value;
    }

    /**
     * Gets the value of the socialSecurityNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSocialSecurityNum() {
        return socialSecurityNum;
    }

    /**
     * Sets the value of the socialSecurityNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSocialSecurityNum(String value) {
        this.socialSecurityNum = value;
    }

    /**
     * Gets the value of the fileNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFileNumber() {
        return fileNumber;
    }

    /**
     * Sets the value of the fileNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFileNumber(String value) {
        this.fileNumber = value;
    }

    /**
     * Gets the value of the birthDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getBirthDate() {
        return birthDate;
    }

    /**
     * Sets the value of the birthDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setBirthDate(XMLGregorianCalendar value) {
        this.birthDate = value;
    }

    /**
     * Gets the value of the postal property.
     * 
     * @return
     *     possible object is
     *     {@link PostalType }
     *     
     */
    public PostalType getPostal() {
        return postal;
    }

    /**
     * Sets the value of the postal property.
     * 
     * @param value
     *     allowed object is
     *     {@link PostalType }
     *     
     */
    public void setPostal(PostalType value) {
        this.postal = value;
    }

}
