//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.01.19 at 10:54:03 AM CST 
//


package gov.va.vba.framework.domain.entities.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}PERSONV" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}PERSONNEL" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}MAILING_ADDRESS" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}TELEPHONE_NUMBER" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}ALIAS_NAME" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}EDUCATION" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}PAGE" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}PERSONNEL_ST" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "personv",
    "personnel",
    "mailingaddress",
    "telephonenumber",
    "aliasname",
    "education",
    "page",
    "personnelst"
})
@XmlRootElement(name = "VADIR")
public class VADIR {

    @XmlElement(name = "PERSONV")
    protected List<PERSONV> personv;
    @XmlElement(name = "PERSONNEL")
    protected List<PERSONNEL> personnel;
    @XmlElement(name = "MAILING_ADDRESS")
    protected List<MAILINGADDRESS> mailingaddress;
    @XmlElement(name = "TELEPHONE_NUMBER")
    protected List<TELEPHONENUMBER> telephonenumber;
    @XmlElement(name = "ALIAS_NAME")
    protected List<ALIASNAME> aliasname;
    @XmlElement(name = "EDUCATION")
    protected List<EDUCATION> education;
    @XmlElement(name = "PAGE")
    protected List<PAGE> page;
    @XmlElement(name = "PERSONNEL_ST")
    protected List<PERSONNELST> personnelst;

    /**
     * Gets the value of the personv property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the personv property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPERSONV().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PERSONV }
     * 
     * 
     */
    public List<PERSONV> getPERSONV() {
        if (personv == null) {
            personv = new ArrayList<PERSONV>();
        }
        return this.personv;
    }

    /**
     * Gets the value of the personnel property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the personnel property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPERSONNEL().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PERSONNEL }
     * 
     * 
     */
    public List<PERSONNEL> getPERSONNEL() {
        if (personnel == null) {
            personnel = new ArrayList<PERSONNEL>();
        }
        return this.personnel;
    }

    /**
     * Gets the value of the mailingaddress property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the mailingaddress property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMAILINGADDRESS().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MAILINGADDRESS }
     * 
     * 
     */
    public List<MAILINGADDRESS> getMAILINGADDRESS() {
        if (mailingaddress == null) {
            mailingaddress = new ArrayList<MAILINGADDRESS>();
        }
        return this.mailingaddress;
    }

    /**
     * Gets the value of the telephonenumber property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the telephonenumber property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTELEPHONENUMBER().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TELEPHONENUMBER }
     * 
     * 
     */
    public List<TELEPHONENUMBER> getTELEPHONENUMBER() {
        if (telephonenumber == null) {
            telephonenumber = new ArrayList<TELEPHONENUMBER>();
        }
        return this.telephonenumber;
    }

    /**
     * Gets the value of the aliasname property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the aliasname property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getALIASNAME().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ALIASNAME }
     * 
     * 
     */
    public List<ALIASNAME> getALIASNAME() {
        if (aliasname == null) {
            aliasname = new ArrayList<ALIASNAME>();
        }
        return this.aliasname;
    }

    /**
     * Gets the value of the education property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the education property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEDUCATION().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EDUCATION }
     * 
     * 
     */
    public List<EDUCATION> getEDUCATION() {
        if (education == null) {
            education = new ArrayList<EDUCATION>();
        }
        return this.education;
    }

    /**
     * Gets the value of the page property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the page property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPAGE().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PAGE }
     * 
     * 
     */
    public List<PAGE> getPAGE() {
        if (page == null) {
            page = new ArrayList<PAGE>();
        }
        return this.page;
    }

    /**
     * Gets the value of the personnelst property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the personnelst property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPERSONNELST().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PERSONNELST }
     * 
     * 
     */
    public List<PERSONNELST> getPERSONNELST() {
        if (personnelst == null) {
            personnelst = new ArrayList<PERSONNELST>();
        }
        return this.personnelst;
    }

}
